#!/bin/bash

# Setup some environmental context for developers
if [ -z "${JAVA_HOME}" ]; then
    if [ -x /usr/libexec/java_home ]; then
        export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
    elif [ -d /usr/lib/jvm/java-8-oracle ]; then
        export JAVA_HOME="/usr/lib/jvm/java-8-oracle"
    elif [ -d /usr/lib/jvm/java-8-openjdk-amd64 ]; then
        export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"
    fi
fi

ATOMIX_ROOT="$(dirname "$(dirname "$0")")"

exec java -jar "$ATOMIX_ROOT/compiler/target/atomix-protoc-gen-4.0.0-SNAPSHOT-shaded.jar" "@"
